### ISSUE TITLE
Add the ability to add unit description

### ISSUE THREAD

**Issue by WhiteFox08** [fparma/fparma-web#4]
for example if you scroll over a element it will provide what that element is for 

e.g  
# Pathfinder Alpha

This is a M-117 and Crew

**Comment by SFAriel** [comment]
How do I upvote.

**Comment by SFAriel** [comment]
I accidently closed the issue, sorry.

**Comment by WhiteFox08** [comment]
nice job noob

**Comment by Cuel** [comment]
Good idea

**Comment by Cuel** [comment]
![pic](http://i.imgur.com/ZQOCXpp.png)

**Comment by WhiteFox08** [comment]
thanks billyt
