### ISSUE TITLE
Username requirements not aligning with Arma3 username standards

### ISSUE THREAD

**Issue by SFAriel** [fparma/fparma-web#6]
"Username must be between 3-24 characters, start with a letter and can only contain (A-Z, a-z, 0-9, -_ and space)" says the website when I try to set my name as =7Cav=SPC.Kovacs.A

**Comment by SFAriel** [comment]
While I am at this, usernames should be editable because they can change at any time.

**Comment by fippefi** [comment]
You should probably just leave your clantag out of the name. Changing your nickname would be a welcome feature, anyway.

**Comment by SFAriel** [comment]
No way dude. Embrace the cav.

**Comment by Cuel** [comment]
Imo usernames should be readable, having a clantag -- I don't agree with this
Changing username is possble but you'd have to contact me. I don't plan on making this possible for users
